-- =============================================================
-- View: Monthly Sales Summary
-- Purpose:
-- Reusable monthly sales dataset for reporting and dashboards.
-- =============================================================

CREATE OR REPLACE VIEW olist.vw_monthly_sales AS

SELECT

    DATE_TRUNC('month', o.order_purchase_timestamp) AS month,

    COUNT(DISTINCT o.order_id) AS total_orders,

    ROUND(SUM(oi.price),2) AS revenue

FROM olist.orders o

JOIN olist.order_items oi
ON o.order_id = oi.order_id

WHERE o.order_status='delivered'

GROUP BY 1

ORDER BY 1;

-- =============================================================
-- View: Product Category Performance
-- Purpose:
-- Revenue generated by each product category.
-- =============================================================

CREATE OR REPLACE VIEW olist.vw_category_sales AS

SELECT

    ct.product_category_name_english,

    COUNT(*) AS items_sold,

    ROUND(SUM(oi.price),2) AS revenue

FROM olist.products p

JOIN olist.order_items oi
ON p.product_id = oi.product_id

LEFT JOIN olist.category_translation ct
ON p.product_category_name = ct.product_category_name

GROUP BY ct.product_category_name_english;


-- =============================================================
-- View: State Sales Summary
-- Purpose:
-- Revenue generated from each customer state.
-- =============================================================

CREATE OR REPLACE VIEW olist.vw_state_sales AS

SELECT

    c.customer_state,

    COUNT(DISTINCT o.order_id) AS total_orders,

    ROUND(SUM(oi.price),2) AS revenue

FROM olist.customers c

JOIN olist.orders o
ON c.customer_id = o.customer_id

JOIN olist.order_items oi
ON o.order_id = oi.order_id

WHERE o.order_status='delivered'

GROUP BY c.customer_state;